### PR TITLE
v2 spec for mapnik-version

### PR DESCRIPTION
**Pull request by mapsam**
- Adds the v2_spec branch for `node-mapnik`
- adds a new geojson fixture for polygons, using US Census data from 2014

### CODE REVIEW

**Comment by springmeyer** [comment]
Great work on this @mapsam. I just committed a few things to clean up cruft I left behind from raster testing/etc.

**Comment by mapsam** [comment]
Very poorly executed `squash` above. Sorry about that!

Regardless, this is ready to merge @springmeyer :smile:

**Comment by jakepruitt** [comment]
(This might not be the place to add this thought, but I just remembered it before falling asleep) - When running these benchmarks to compare the v2 branch, should we do this on a `morec2` to homogenize the data and make it reproducible?

**Comment by springmeyer** [comment]
@mapsam: yes, we want to have this repo work with XML testcases that pull both vector and raster data. So a testcase organization style that keeps each in a subfolder sounds good.

@jakepruitt - good point about running on AWS for more meaningful results. At the same time I like running these locally and we should make it easy to do both: so I think the actionable things are 1) ensure that the report logs basic operating system info, 2) @mapsam plans to run things on AWS.

**Comment by mapsam** [comment]
Going to push this conversation into a ticket @jakepruitt @springmeyer so we can merge this and not lose it! https://github.com/mapbox/gdal-tiling-bench/issues/18

**Pull request merged**
